// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/h2p2f/loyalty-gophermart/internal/gophermart/models"
)

// DataBaser is an autogenerated mock type for the DataBaser type
type DataBaser struct {
	mock.Mock
}

// CheckUniqueOrder provides a mock function with given fields: ctx, order
func (_m *DataBaser) CheckUniqueOrder(ctx context.Context, order string) (string, bool) {
	ret := _m.Called(ctx, order)

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, bool)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// FindPassByLogin provides a mock function with given fields: ctx, login
func (_m *DataBaser) FindPassByLogin(ctx context.Context, login string) (string, error) {
	ret := _m.Called(ctx, login)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, login)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllWithdraws provides a mock function with given fields: ctx, login
func (_m *DataBaser) GetAllWithdraws(ctx context.Context, login string) []byte {
	ret := _m.Called(ctx, login)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// GetBalance provides a mock function with given fields: ctx, login
func (_m *DataBaser) GetBalance(ctx context.Context, login string) (float64, error) {
	ret := _m.Called(ctx, login)

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, login)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrdersByUser provides a mock function with given fields: ctx, login
func (_m *DataBaser) GetOrdersByUser(ctx context.Context, login string) ([]byte, error) {
	ret := _m.Called(ctx, login)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSumOfAllWithdraws provides a mock function with given fields: ctx, login
func (_m *DataBaser) GetSumOfAllWithdraws(ctx context.Context, login string) float64 {
	ret := _m.Called(ctx, login)

	var r0 float64
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, login)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// NewOrder provides a mock function with given fields: ctx, login, order
func (_m *DataBaser) NewOrder(ctx context.Context, login string, order models.Order) error {
	ret := _m.Called(ctx, login, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.Order) error); ok {
		r0 = rf(ctx, login, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUser provides a mock function with given fields: ctx, user
func (_m *DataBaser) NewUser(ctx context.Context, user models.User) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWithdraw provides a mock function with given fields: ctx, login, withdraw
func (_m *DataBaser) NewWithdraw(ctx context.Context, login string, withdraw models.Withdraw) error {
	ret := _m.Called(ctx, login, withdraw)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.Withdraw) error); ok {
		r0 = rf(ctx, login, withdraw)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDataBaser interface {
	mock.TestingT
	Cleanup(func())
}

// NewDataBaser creates a new instance of DataBaser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDataBaser(t mockConstructorTestingTNewDataBaser) *DataBaser {
	mock := &DataBaser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
